simulation:
  timestep_simulation: 0.002 # 0.00125
  #timestep_policy: 0.005
  framerate: 60
  duration: 7
  framerate: 60

robot:
  default_joint_angles: [0.0, 0.9, -1.7, 0.0, 0.9, -1.7, 0.0, 0.9, -1.7, 0.0, 0.9, -1.7]
  kp_custom: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
  kd_custom: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  mu_vRange: [0.0, 0.3]
  FsRange: [0.0, 2.5]
  default_mid: [0.0, 0.9, -1.7]

actions:
  bounds:
    low: -35.0
    high: 35.0
    special_high: 45.0

scaling:
  body_ang_vel: 0.25
  commands: 2.0
  gravity_body: 1.0
  joint_angles: 1.0
  joint_velocities: 0.05
  actions: 1.0

paths:
  checkpoint_path: nn/SoloTerrain.pth # friction_model_2.pth # friction_model_2.pth # friction_model_1.pth # test_steps.pth # SoloTerrain.pth # nn/SoloTerrain_lower_frequency.pth
